// Mock siwe before importing the route so generateNonce is controllable
jest.mock('siwe', () => ({
  generateNonce: jest.fn(),
}));

// Mock next/server
jest.mock('next/server', () => ({
  NextResponse: {
    json: jest.fn((body, init) => ({
      status: init?.status || 200,
      json: async () => body,
    })),
  },
}));

import { GET } from '../auth/nonce/route';
import { generateNonce } from 'siwe';

const mockGenerateNonce = generateNonce as jest.MockedFunction<typeof generateNonce>;

describe('GET /api/auth/nonce', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('should return a nonce generated by siwe', async () => {
    mockGenerateNonce.mockReturnValue('abc123nonce');

    const res = await GET();
    const data = await res.json();

    expect(res.status).toBe(200);
    expect(data.nonce).toBe('abc123nonce');
    expect(mockGenerateNonce).toHaveBeenCalledTimes(1);
  });

  it('should call generateNonce exactly once per request', async () => {
    mockGenerateNonce.mockReturnValue('unique-nonce');

    await GET();

    expect(mockGenerateNonce).toHaveBeenCalledTimes(1);
  });

  it('should return a different nonce each call (when generateNonce returns unique values)', async () => {
    mockGenerateNonce
      .mockReturnValueOnce('nonce-first')
      .mockReturnValueOnce('nonce-second');

    const res1 = await GET();
    const data1 = await res1.json();

    const res2 = await GET();
    const data2 = await res2.json();

    expect(data1.nonce).toBe('nonce-first');
    expect(data2.nonce).toBe('nonce-second');
    expect(data1.nonce).not.toBe(data2.nonce);
  });

  it('should return an object with exactly a nonce property', async () => {
    mockGenerateNonce.mockReturnValue('test-nonce-value');

    const res = await GET();
    const data = await res.json();

    expect(Object.keys(data)).toEqual(['nonce']);
  });

  it('should return status 200', async () => {
    mockGenerateNonce.mockReturnValue('some-nonce');

    const res = await GET();

    expect(res.status).toBe(200);
  });
});